### ISSUE TITLE
[BUG] Plugin not supported

### ISSUE THREAD

**Issue by latitude23** [amongst-us/qbit-plugins#1]
**Describe the bug**
QBittorents V4.6.3 64bits says your search plugin is not supported

**To Reproduce**
1. Go to 'Search plugin install'
2.  choose whatever 'local file' or 'web link'
3. as results you get a windows 'search plugin cannot be installed. incompatible'

**Comment by amongst-us** [comment]
Hi! Thanks for the report.
Please try to follow the template -- with the given details, I can't try and recreate your problem. Which Python version are you using? Which link did you input with web link/which file for local file?

**Comment by Messier43** [comment]
I have the same issue while following the same steps 
The link : https://raw.githubusercontent.com/amongst-us/qbit-plugins/main/yts_mx.py
Python : 3.11.7
On a fresh install of Qbittorrent

**Comment by amongst-us** [comment]
Since I wrote the plugin fairly recently, it looks like I used something exclusive to python 3.12 (as indicated on the [unofficial search plugins](https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins) page) -- I'll have a look at it and see if it's something I can make backwards compatible.

**Comment by amongst-us** [comment]
I've tested it now with Python 3.11.7 and 3.11.8, and it seems to be working. Give this a go https://raw.githubusercontent.com/amongst-us/qbit-plugins/main/yts_mx/yts_mx.py and let me know?
